name: Test

on: [push]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: RSpec
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bundle exec rspec

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: RuboCop
      run: |
        bundle exec rubocop
